// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBKwBcE-qX3AC8xcyEU-se764Vrqhe4V4',
    appId: '1:867709926525:web:7408d6c2493f4662a6c514',
    messagingSenderId: '867709926525',
    projectId: 'pcpslife',
    authDomain: 'pcpslife.firebaseapp.com',
    storageBucket: 'pcpslife.firebasestorage.app',
    measurementId: 'G-BFQNLRYN66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiMNPNZ0cKbXtaQhFsF64-pkWI28DP8ls',
    appId: '1:867709926525:android:78a0d5f95579e5ffa6c514',
    messagingSenderId: '867709926525',
    projectId: 'pcpslife',
    storageBucket: 'pcpslife.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCW4RCfzlU-YZQQucH_N2cboaNBSrELI8',
    appId: '1:867709926525:ios:187f09b8e5240f51a6c514',
    messagingSenderId: '867709926525',
    projectId: 'pcpslife',
    storageBucket: 'pcpslife.firebasestorage.app',
    iosBundleId: 'com.lbef.edu.np.lbef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCW4RCfzlU-YZQQucH_N2cboaNBSrELI8',
    appId: '1:867709926525:ios:187f09b8e5240f51a6c514',
    messagingSenderId: '867709926525',
    projectId: 'pcpslife',
    storageBucket: 'pcpslife.firebasestorage.app',
    iosBundleId: 'com.lbef.edu.np.lbef',
  );
}
